"""Add requirement system

Revision ID: 020c03be0c03
Revises: f7667f591cfa
Create Date: 2026-09-07 21:25:21.631543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020c03be0c03'
down_revision: Union[str, Sequence[str], None] = 'f7667f591cfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('requirement_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animation_id', sa.Integer(), nullable=False),
    sa.Column('logical_operator', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['animation_id'], ['animations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_group_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(length=5), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['requirement_group_id'], ['requirement_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirements')
    op.drop_table('requirement_groups')
    op.drop_table('attributes')
    # ### end Alembic commands ###
