"""Add animations table

Revision ID: f7667f591cfa
Revises: 523ac2eeb664
Create Date: 2026-09-07 20:12:08.333067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7667f591cfa'
down_revision: Union[str, Sequence[str], None] = '523ac2eeb664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_edition_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('introduced_season_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['animation_categories.id'], ),
    sa.ForeignKeyConstraint(['game_edition_id'], ['game_editions.id'], ),
    sa.ForeignKeyConstraint(['introduced_season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animations')
    # ### end Alembic commands ###
